version: "3"
services:
  app:
    container_name: graphql-app
    restart: always
    build: .
    networks:
      - graphql-app-network
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - GRAPHQL_PATH=/graphql
      - NODE_ENV=${NODE_ENV}
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=mongodb://test:${MONGODB_PASSWORD}@mongodb:27017/ncbi
    env_file: .env
    depends_on:
      - mongodb
      - redis
  # MongoDB container
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    networks:
      - graphql-app-network
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_INIT_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-db-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
  # Redis container
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      - graphql-app-network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always

networks:
  graphql-app-network:
    driver: bridge
