services:
  app:
    container_name: graphql-app
    restart: always
    build: .
    networks:
      - graphql-app-network
    ports:
      - "4002:4002"
    env_file: .env
    depends_on:
      - mongodb
      - redis
  # MongoDB container
  mongodb:
    image: "mongo:5.0.3"
    container_name: "mongodb"
    networks:
      - graphql-app-network
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_INIT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-db-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
  # Redis container
  redis:
    image: "redis:6.2.6"
    container_name: redis
    networks:
      - graphql-app-network
    ports:
      - "6379:6379"
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

networks:
  graphql-app-network:
    driver: bridge
